# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoService.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(10, 60, 321, 211))
        self.listWidget.setObjectName("listWidget")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 5, 182, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.search_client_btn = QtWidgets.QPushButton(self.tab)
        self.search_client_btn.setGeometry(QtCore.QRect(300, 30, 31, 31))
        self.search_client_btn.setStyleSheet("background:white;")
        self.search_client_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_client_btn.setIcon(icon)
        self.search_client_btn.setIconSize(QtCore.QSize(16, 16))
        self.search_client_btn.setObjectName("search_client_btn")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 300, 751, 251))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 721, 179))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.bd_line_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.bd_line_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.bd_line_2.setFont(font)
        self.bd_line_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bd_line_2.setReadOnly(False)
        self.bd_line_2.setObjectName("bd_line_2")
        self.gridLayout_2.addWidget(self.bd_line_2, 2, 1, 1, 1)
        self.phone_line_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.phone_line_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.phone_line_2.setFont(font)
        self.phone_line_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.phone_line_2.setReadOnly(False)
        self.phone_line_2.setObjectName("phone_line_2")
        self.gridLayout_2.addWidget(self.phone_line_2, 4, 1, 1, 1)
        self.addr_line_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.addr_line_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.addr_line_2.setFont(font)
        self.addr_line_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.addr_line_2.setReadOnly(False)
        self.addr_line_2.setObjectName("addr_line_2")
        self.gridLayout_2.addWidget(self.addr_line_2, 3, 1, 1, 1)
        self.f_name_line_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.f_name_line_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.f_name_line_2.setFont(font)
        self.f_name_line_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f_name_line_2.setReadOnly(False)
        self.f_name_line_2.setObjectName("f_name_line_2")
        self.gridLayout_2.addWidget(self.f_name_line_2, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.s_name_line_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.s_name_line_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.s_name_line_2.setFont(font)
        self.s_name_line_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s_name_line_2.setReadOnly(False)
        self.s_name_line_2.setObjectName("s_name_line_2")
        self.gridLayout_2.addWidget(self.s_name_line_2, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.info_label = QtWidgets.QLabel(self.groupBox)
        self.info_label.setGeometry(QtCore.QRect(20, 212, 611, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.info_label.setFont(font)
        self.info_label.setStyleSheet("color:orange")
        self.info_label.setObjectName("info_label")
        self.add_btn = QtWidgets.QPushButton(self.groupBox)
        self.add_btn.setGeometry(QtCore.QRect(660, 220, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.edit_btn = QtWidgets.QPushButton(self.tab)
        self.edit_btn.setGeometry(QtCore.QRect(520, 280, 75, 23))
        self.edit_btn.setObjectName("edit_btn")
        self.delete_btn = QtWidgets.QPushButton(self.tab)
        self.delete_btn.setGeometry(QtCore.QRect(130, 280, 75, 23))
        self.delete_btn.setObjectName("delete_btn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 0, 421, 271))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 401, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.bd_line = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.bd_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.bd_line.setFont(font)
        self.bd_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bd_line.setReadOnly(True)
        self.bd_line.setObjectName("bd_line")
        self.gridLayout.addWidget(self.bd_line, 3, 1, 1, 1)
        self.s_name_line = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.s_name_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.s_name_line.setFont(font)
        self.s_name_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s_name_line.setReadOnly(True)
        self.s_name_line.setObjectName("s_name_line")
        self.gridLayout.addWidget(self.s_name_line, 2, 1, 1, 1)
        self.f_name_line = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.f_name_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.f_name_line.setFont(font)
        self.f_name_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f_name_line.setReadOnly(True)
        self.f_name_line.setObjectName("f_name_line")
        self.gridLayout.addWidget(self.f_name_line, 1, 1, 1, 1)
        self.id_line = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.id_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.id_line.setFont(font)
        self.id_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.id_line.setReadOnly(True)
        self.id_line.setObjectName("id_line")
        self.gridLayout.addWidget(self.id_line, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.phone_line = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.phone_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.phone_line.setFont(font)
        self.phone_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.phone_line.setReadOnly(True)
        self.phone_line.setObjectName("phone_line")
        self.gridLayout.addWidget(self.phone_line, 5, 1, 1, 1)
        self.addr_line = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.addr_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.addr_line.setFont(font)
        self.addr_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.addr_line.setReadOnly(True)
        self.addr_line.setObjectName("addr_line")
        self.gridLayout.addWidget(self.addr_line, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(10, 5, 182, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.carslistWidget = QtWidgets.QListWidget(self.tab_2)
        self.carslistWidget.setGeometry(QtCore.QRect(10, 60, 321, 221))
        self.carslistWidget.setObjectName("carslistWidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(340, 0, 421, 281))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 401, 244))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.car_make_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_make_label.setFont(font)
        self.car_make_label.setObjectName("car_make_label")
        self.gridLayout_3.addWidget(self.car_make_label, 1, 0, 1, 1)
        self.car_id_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_id_label.setFont(font)
        self.car_id_label.setObjectName("car_id_label")
        self.gridLayout_3.addWidget(self.car_id_label, 0, 0, 1, 1)
        self.car_client_f_name_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_client_f_name_label.setFont(font)
        self.car_client_f_name_label.setObjectName("car_client_f_name_label")
        self.gridLayout_3.addWidget(self.car_client_f_name_label, 6, 0, 1, 1)
        self.car_id_line = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.car_id_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_id_line.setFont(font)
        self.car_id_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_id_line.setReadOnly(True)
        self.car_id_line.setObjectName("car_id_line")
        self.gridLayout_3.addWidget(self.car_id_line, 0, 1, 1, 1)
        self.car_model_label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_label_2.setFont(font)
        self.car_model_label_2.setObjectName("car_model_label_2")
        self.gridLayout_3.addWidget(self.car_model_label_2, 3, 0, 1, 1)
        self.car_make_line = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.car_make_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_make_line.setFont(font)
        self.car_make_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_make_line.setReadOnly(True)
        self.car_make_line.setObjectName("car_make_line")
        self.gridLayout_3.addWidget(self.car_make_line, 1, 1, 1, 1)
        self.car_client_f_name_line = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.car_client_f_name_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_client_f_name_line.setFont(font)
        self.car_client_f_name_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_client_f_name_line.setReadOnly(True)
        self.car_client_f_name_line.setObjectName("car_client_f_name_line")
        self.gridLayout_3.addWidget(self.car_client_f_name_line, 6, 1, 1, 1)
        self.car_model_line = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.car_model_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_line.setFont(font)
        self.car_model_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_model_line.setReadOnly(True)
        self.car_model_line.setObjectName("car_model_line")
        self.gridLayout_3.addWidget(self.car_model_line, 2, 1, 1, 1)
        self.car_client_id_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_client_id_label.setFont(font)
        self.car_client_id_label.setObjectName("car_client_id_label")
        self.gridLayout_3.addWidget(self.car_client_id_label, 5, 0, 1, 1)
        self.car_client_s_name_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_client_s_name_label.setFont(font)
        self.car_client_s_name_label.setObjectName("car_client_s_name_label")
        self.gridLayout_3.addWidget(self.car_client_s_name_label, 7, 0, 1, 1)
        self.car_model_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_label.setFont(font)
        self.car_model_label.setObjectName("car_model_label")
        self.gridLayout_3.addWidget(self.car_model_label, 2, 0, 1, 1)
        self.car_client_id_line = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.car_client_id_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_client_id_line.setFont(font)
        self.car_client_id_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_client_id_line.setReadOnly(True)
        self.car_client_id_line.setObjectName("car_client_id_line")
        self.gridLayout_3.addWidget(self.car_client_id_line, 5, 1, 1, 1)
        self.car_year_line = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.car_year_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_year_line.setFont(font)
        self.car_year_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_year_line.setReadOnly(True)
        self.car_year_line.setObjectName("car_year_line")
        self.gridLayout_3.addWidget(self.car_year_line, 3, 1, 1, 1)
        self.car_client_s_name_line = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.car_client_s_name_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_client_s_name_line.setFont(font)
        self.car_client_s_name_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_client_s_name_line.setReadOnly(True)
        self.car_client_s_name_line.setObjectName("car_client_s_name_line")
        self.gridLayout_3.addWidget(self.car_client_s_name_line, 7, 1, 1, 1)
        self.car_model_label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_label_3.setFont(font)
        self.car_model_label_3.setObjectName("car_model_label_3")
        self.gridLayout_3.addWidget(self.car_model_label_3, 4, 0, 1, 1)
        self.car_vin_line = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.car_vin_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_vin_line.setFont(font)
        self.car_vin_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_vin_line.setReadOnly(True)
        self.car_vin_line.setObjectName("car_vin_line")
        self.gridLayout_3.addWidget(self.car_vin_line, 4, 1, 1, 1)
        self.edit_car_btn = QtWidgets.QPushButton(self.tab_2)
        self.edit_car_btn.setGeometry(QtCore.QRect(520, 290, 75, 21))
        self.edit_car_btn.setObjectName("edit_car_btn")
        self.delete_car_btn = QtWidgets.QPushButton(self.tab_2)
        self.delete_car_btn.setGeometry(QtCore.QRect(130, 290, 75, 21))
        self.delete_car_btn.setObjectName("delete_car_btn")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 310, 751, 241))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.car_info_label = QtWidgets.QLabel(self.groupBox_4)
        self.car_info_label.setGeometry(QtCore.QRect(20, 202, 611, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_info_label.setFont(font)
        self.car_info_label.setStyleSheet("color:orange")
        self.car_info_label.setObjectName("car_info_label")
        self.add_car_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.add_car_btn.setGeometry(QtCore.QRect(640, 200, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.add_car_btn.setFont(font)
        self.add_car_btn.setObjectName("add_car_btn")
        self.car_model_line_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.car_model_line_2.setEnabled(True)
        self.car_model_line_2.setGeometry(QtCore.QRect(110, 71, 271, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_line_2.setFont(font)
        self.car_model_line_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_model_line_2.setReadOnly(False)
        self.car_model_line_2.setObjectName("car_model_line_2")
        self.car_model_label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.car_model_label_5.setGeometry(QtCore.QRect(30, 98, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_label_5.setFont(font)
        self.car_model_label_5.setObjectName("car_model_label_5")
        self.car_model_label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.car_model_label_4.setGeometry(QtCore.QRect(30, 129, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_label_4.setFont(font)
        self.car_model_label_4.setObjectName("car_model_label_4")
        self.car_client_id_label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.car_client_id_label_2.setGeometry(QtCore.QRect(30, 160, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_client_id_label_2.setFont(font)
        self.car_client_id_label_2.setObjectName("car_client_id_label_2")
        self.car_year_line_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.car_year_line_2.setEnabled(True)
        self.car_year_line_2.setGeometry(QtCore.QRect(110, 102, 271, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_year_line_2.setFont(font)
        self.car_year_line_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_year_line_2.setReadOnly(False)
        self.car_year_line_2.setObjectName("car_year_line_2")
        self.car_make_label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.car_make_label_2.setGeometry(QtCore.QRect(30, 36, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_make_label_2.setFont(font)
        self.car_make_label_2.setObjectName("car_make_label_2")
        self.car_model_label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.car_model_label_6.setGeometry(QtCore.QRect(30, 67, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_label_6.setFont(font)
        self.car_model_label_6.setObjectName("car_model_label_6")
        self.car_client_id_line_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.car_client_id_line_2.setEnabled(True)
        self.car_client_id_line_2.setGeometry(QtCore.QRect(110, 164, 271, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_client_id_line_2.setFont(font)
        self.car_client_id_line_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_client_id_line_2.setReadOnly(True)
        self.car_client_id_line_2.setObjectName("car_client_id_line_2")
        self.car_vin_line_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.car_vin_line_2.setEnabled(True)
        self.car_vin_line_2.setGeometry(QtCore.QRect(110, 133, 271, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_vin_line_2.setFont(font)
        self.car_vin_line_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_vin_line_2.setReadOnly(False)
        self.car_vin_line_2.setObjectName("car_vin_line_2")
        self.car_make_line_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.car_make_line_2.setEnabled(True)
        self.car_make_line_2.setGeometry(QtCore.QRect(110, 40, 271, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_make_line_2.setFont(font)
        self.car_make_line_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.car_make_line_2.setReadOnly(False)
        self.car_make_line_2.setObjectName("car_make_line_2")
        self.client_car_listWidget = QtWidgets.QListWidget(self.groupBox_4)
        self.client_car_listWidget.setGeometry(QtCore.QRect(400, 80, 321, 111))
        self.client_car_listWidget.setObjectName("client_car_listWidget")
        self.search_car_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.search_car_btn.setGeometry(QtCore.QRect(690, 50, 31, 31))
        self.search_car_btn.setStyleSheet("background:white;")
        self.search_car_btn.setText("")
        self.search_car_btn.setIcon(icon)
        self.search_car_btn.setIconSize(QtCore.QSize(16, 16))
        self.search_car_btn.setObjectName("search_car_btn")
        self.search_car_client = QtWidgets.QLineEdit(self.groupBox_4)
        self.search_car_client.setGeometry(QtCore.QRect(400, 50, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.search_car_client.setFont(font)
        self.search_car_client.setObjectName("search_car_client")
        self.car_make_label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.car_make_label_3.setGeometry(QtCore.QRect(400, 25, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_make_label_3.setFont(font)
        self.car_make_label_3.setObjectName("car_make_label_3")
        self.search_car_button = QtWidgets.QPushButton(self.tab_2)
        self.search_car_button.setGeometry(QtCore.QRect(300, 30, 31, 31))
        self.search_car_button.setStyleSheet("background:white;")
        self.search_car_button.setText("")
        self.search_car_button.setIcon(icon)
        self.search_car_button.setIconSize(QtCore.QSize(16, 16))
        self.search_car_button.setObjectName("search_car_button")
        self.search_car_line = QtWidgets.QLineEdit(self.tab_2)
        self.search_car_line.setGeometry(QtCore.QRect(10, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.search_car_line.setFont(font)
        self.search_car_line.setObjectName("search_car_line")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(10, 5, 182, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setGeometry(QtCore.QRect(340, 0, 421, 271))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_9)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 30, 401, 231))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.prod_info_line = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.prod_info_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.prod_info_line.setFont(font)
        self.prod_info_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prod_info_line.setReadOnly(True)
        self.prod_info_line.setObjectName("prod_info_line")
        self.gridLayout_7.addWidget(self.prod_info_line, 3, 1, 1, 1)
        self.car_model_label_15 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_label_15.setFont(font)
        self.car_model_label_15.setObjectName("car_model_label_15")
        self.gridLayout_7.addWidget(self.car_model_label_15, 4, 0, 1, 1)
        self.car_make_label_7 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_make_label_7.setFont(font)
        self.car_make_label_7.setObjectName("car_make_label_7")
        self.gridLayout_7.addWidget(self.car_make_label_7, 1, 0, 1, 1)
        self.car_model_label_13 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_label_13.setFont(font)
        self.car_model_label_13.setObjectName("car_model_label_13")
        self.gridLayout_7.addWidget(self.car_model_label_13, 3, 0, 1, 1)
        self.product_id_line = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.product_id_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.product_id_line.setFont(font)
        self.product_id_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.product_id_line.setReadOnly(True)
        self.product_id_line.setObjectName("product_id_line")
        self.gridLayout_7.addWidget(self.product_id_line, 0, 1, 1, 1)
        self.car_model_label_14 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_model_label_14.setFont(font)
        self.car_model_label_14.setObjectName("car_model_label_14")
        self.gridLayout_7.addWidget(self.car_model_label_14, 2, 0, 1, 1)
        self.prod_price_line = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.prod_price_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.prod_price_line.setFont(font)
        self.prod_price_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prod_price_line.setReadOnly(True)
        self.prod_price_line.setObjectName("prod_price_line")
        self.gridLayout_7.addWidget(self.prod_price_line, 4, 1, 1, 1)
        self.product_name_line = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.product_name_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.product_name_line.setFont(font)
        self.product_name_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.product_name_line.setReadOnly(True)
        self.product_name_line.setObjectName("product_name_line")
        self.gridLayout_7.addWidget(self.product_name_line, 1, 1, 1, 1)
        self.car_client_id_label_5 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_client_id_label_5.setFont(font)
        self.car_client_id_label_5.setObjectName("car_client_id_label_5")
        self.gridLayout_7.addWidget(self.car_client_id_label_5, 5, 0, 1, 1)
        self.prod_quant_line = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.prod_quant_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.prod_quant_line.setFont(font)
        self.prod_quant_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prod_quant_line.setReadOnly(True)
        self.prod_quant_line.setObjectName("prod_quant_line")
        self.gridLayout_7.addWidget(self.prod_quant_line, 5, 1, 1, 1)
        self.car_id_label_3 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.car_id_label_3.setFont(font)
        self.car_id_label_3.setObjectName("car_id_label_3")
        self.gridLayout_7.addWidget(self.car_id_label_3, 0, 0, 1, 1)
        self.manufacturer_line = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.manufacturer_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.manufacturer_line.setFont(font)
        self.manufacturer_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.manufacturer_line.setReadOnly(True)
        self.manufacturer_line.setObjectName("manufacturer_line")
        self.gridLayout_7.addWidget(self.manufacturer_line, 2, 1, 1, 1)
        self.edit_product_btn = QtWidgets.QPushButton(self.tab_3)
        self.edit_product_btn.setGeometry(QtCore.QRect(520, 280, 75, 21))
        self.edit_product_btn.setObjectName("edit_product_btn")
        self.productslistWidget = QtWidgets.QListWidget(self.tab_3)
        self.productslistWidget.setGeometry(QtCore.QRect(10, 60, 321, 211))
        self.productslistWidget.setObjectName("productslistWidget")
        self.search_product_line = QtWidgets.QLineEdit(self.tab_3)
        self.search_product_line.setGeometry(QtCore.QRect(10, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.search_product_line.setFont(font)
        self.search_product_line.setObjectName("search_product_line")
        self.search_product_button = QtWidgets.QPushButton(self.tab_3)
        self.search_product_button.setGeometry(QtCore.QRect(300, 30, 31, 31))
        self.search_product_button.setStyleSheet("background:white;")
        self.search_product_button.setText("")
        self.search_product_button.setIcon(icon)
        self.search_product_button.setIconSize(QtCore.QSize(16, 16))
        self.search_product_button.setObjectName("search_product_button")
        self.delete_product_btn = QtWidgets.QPushButton(self.tab_3)
        self.delete_product_btn.setGeometry(QtCore.QRect(130, 280, 75, 21))
        self.delete_product_btn.setObjectName("delete_product_btn")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 300, 751, 251))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.prod_info_label = QtWidgets.QLabel(self.groupBox_10)
        self.prod_info_label.setGeometry(QtCore.QRect(20, 220, 611, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.prod_info_label.setFont(font)
        self.prod_info_label.setStyleSheet("color:orange")
        self.prod_info_label.setObjectName("prod_info_label")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_10)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(20, 28, 711, 181))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 0, 1, 1)
        self.new_prod_info_line = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.new_prod_info_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.new_prod_info_line.setFont(font)
        self.new_prod_info_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.new_prod_info_line.setReadOnly(False)
        self.new_prod_info_line.setObjectName("new_prod_info_line")
        self.gridLayout_8.addWidget(self.new_prod_info_line, 2, 1, 1, 1)
        self.new_prod_quant_line = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.new_prod_quant_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.new_prod_quant_line.setFont(font)
        self.new_prod_quant_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.new_prod_quant_line.setReadOnly(False)
        self.new_prod_quant_line.setObjectName("new_prod_quant_line")
        self.gridLayout_8.addWidget(self.new_prod_quant_line, 4, 1, 1, 1)
        self.new_prod_price_line = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.new_prod_price_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.new_prod_price_line.setFont(font)
        self.new_prod_price_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.new_prod_price_line.setReadOnly(False)
        self.new_prod_price_line.setObjectName("new_prod_price_line")
        self.gridLayout_8.addWidget(self.new_prod_price_line, 3, 1, 1, 1)
        self.new_prod_name_line = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.new_prod_name_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.new_prod_name_line.setFont(font)
        self.new_prod_name_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.new_prod_name_line.setReadOnly(False)
        self.new_prod_name_line.setObjectName("new_prod_name_line")
        self.gridLayout_8.addWidget(self.new_prod_name_line, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 2, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 1, 0, 1, 1)
        self.new_prod_man_line = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.new_prod_man_line.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.new_prod_man_line.setFont(font)
        self.new_prod_man_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.new_prod_man_line.setReadOnly(False)
        self.new_prod_man_line.setObjectName("new_prod_man_line")
        self.gridLayout_8.addWidget(self.new_prod_man_line, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 4, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 3, 0, 1, 1)
        self.add_prod_btn = QtWidgets.QPushButton(self.groupBox_10)
        self.add_prod_btn.setGeometry(QtCore.QRect(650, 220, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.add_prod_btn.setFont(font)
        self.add_prod_btn.setObjectName("add_prod_btn")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Clients:"))
        self.groupBox.setTitle(_translate("MainWindow", "New Client:"))
        self.label_9.setText(_translate("MainWindow", "Client Firstname:"))
        self.label_11.setText(_translate("MainWindow", "Client Birthdate:"))
        self.label_8.setText(_translate("MainWindow", "Client Secondname:"))
        self.label_13.setText(_translate("MainWindow", "Client Phone:"))
        self.label_10.setText(_translate("MainWindow", "Client Address:"))
        self.info_label.setText(_translate("MainWindow", "INFO"))
        self.add_btn.setText(_translate("MainWindow", "ADD"))
        self.edit_btn.setText(_translate("MainWindow", "EDIT"))
        self.delete_btn.setText(_translate("MainWindow", "DELETE"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Info:"))
        self.label_3.setText(_translate("MainWindow", "Client Secondname:"))
        self.label_2.setText(_translate("MainWindow", "Client Firstname:"))
        self.label_5.setText(_translate("MainWindow", "Client Address:"))
        self.label_4.setText(_translate("MainWindow", "Client Birthdate:"))
        self.label.setText(_translate("MainWindow", "Client ID:"))
        self.label_6.setText(_translate("MainWindow", "Client Phone:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Clients"))
        self.label_12.setText(_translate("MainWindow", "Cars:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Info:"))
        self.car_make_label.setText(_translate("MainWindow", "Car Make:"))
        self.car_id_label.setText(_translate("MainWindow", "Car ID:"))
        self.car_client_f_name_label.setText(_translate("MainWindow", "Client Firstname:"))
        self.car_model_label_2.setText(_translate("MainWindow", "Car Year:"))
        self.car_client_id_label.setText(_translate("MainWindow", "Client ID:"))
        self.car_client_s_name_label.setText(_translate("MainWindow", "Client Secondname:"))
        self.car_model_label.setText(_translate("MainWindow", "Car Model:"))
        self.car_model_label_3.setText(_translate("MainWindow", "Car VIN:"))
        self.edit_car_btn.setText(_translate("MainWindow", "EDIT"))
        self.delete_car_btn.setText(_translate("MainWindow", "DELETE"))
        self.groupBox_4.setTitle(_translate("MainWindow", "New Car:"))
        self.car_info_label.setText(_translate("MainWindow", "INFO"))
        self.add_car_btn.setText(_translate("MainWindow", "ADD"))
        self.car_model_label_5.setText(_translate("MainWindow", "Car Year:"))
        self.car_model_label_4.setText(_translate("MainWindow", "Car VIN:"))
        self.car_client_id_label_2.setText(_translate("MainWindow", "Client ID:"))
        self.car_make_label_2.setText(_translate("MainWindow", "Car Make:"))
        self.car_model_label_6.setText(_translate("MainWindow", "Car Model:"))
        self.car_make_label_3.setText(_translate("MainWindow", "Choose Client:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Cars"))
        self.label_27.setText(_translate("MainWindow", "Products:"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Info:"))
        self.car_model_label_15.setText(_translate("MainWindow", "Product Price:"))
        self.car_make_label_7.setText(_translate("MainWindow", "Product Name:"))
        self.car_model_label_13.setText(_translate("MainWindow", "Product Info:"))
        self.car_model_label_14.setText(_translate("MainWindow", "Manufacturer:"))
        self.car_client_id_label_5.setText(_translate("MainWindow", "Quantity:"))
        self.car_id_label_3.setText(_translate("MainWindow", "Product ID:"))
        self.edit_product_btn.setText(_translate("MainWindow", "EDIT"))
        self.delete_product_btn.setText(_translate("MainWindow", "DELETE"))
        self.groupBox_10.setTitle(_translate("MainWindow", "New Product:"))
        self.prod_info_label.setText(_translate("MainWindow", "INFO"))
        self.label_28.setText(_translate("MainWindow", "Product Name:"))
        self.label_29.setText(_translate("MainWindow", "Product Info:"))
        self.label_30.setText(_translate("MainWindow", "Manufacturer:"))
        self.label_31.setText(_translate("MainWindow", "Quantity:"))
        self.label_32.setText(_translate("MainWindow", "Product Price:"))
        self.add_prod_btn.setText(_translate("MainWindow", "ADD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Products"))
